import { palette } from "./palette";

export const typography = {
  h1: {
    fontFamily: "Roboto-Bold",
    fontSize: "22px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 0.78,
    letterSpacing: "normal",
    textAlign: "center",
    color: "#013eb7",
    textTransform: "capatalize",
  },
  h2: {
    fontFamily: "Montserrat-Medium",
    fontSize: "18px",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "center",
    color: '#fff',
  },
  h3: {
    fontFamily: "Roboto-Medium",
    fontSize: "16px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "20px",
    letterSpacing: "0.73px",
    textAlign: "center",
    color: "rgba(0, 0, 0, 0.85)",
  },

  h6: {
    fontFamily: "Roboto-Light",
    fontSize: "22px",
    fontWeight: 300,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "center",
    color: "#000000",
  },

  subtitle1: {
    fontFamily: "Roboto-Medium",
    fontSize: "12px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 1.33,
    letterSpacing: "normal",
    textAlign: "center",
    color: "#656464",
  },

  subtitle2: {
    fontFamily: "Roboto-Regular",
    fontSize: "13px",
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 1.25,
    letterSpacing: "1.92px",
    textAlign: "left",
    color: "#000",
  },
  subtitle3: {
    fontFamily: "Roboto-Regular",
    fontSize: "16px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "1.6px",
    textAlign: "left",
    color: "#333843",
  },
  subtitle4: {
    fontFamily: "Roboto-Italic",
    fontSize: "16px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 1.25,
    letterSpacing: "normal",
    textAlign: "left",
    color: palette.primary.main,
  },
  subtitle5: {
    fontFamily: "Roboto-Light",
    fontSize: "16px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 2.19,
    letterSpacing: 1.3,
    textAlign: "center",
    color: "#090909",
  },
};
